import type { PacketFormData } from "../types/packet.types";
import { packetDefaults } from "../utils/packet-defaults";

// A representative filled packet used for the demo PDF and for verification.
export const sampleData: PacketFormData = {
  ...packetDefaults,
  intake: {
    ...packetDefaults.intake,
    petitionerFirstName: "Jane",
    petitionerMiddleName: "A.",
    petitionerLastName: "Doe",
    petitionerStreet: "123 Example Street",
    petitionerCity: "Riverside",
    petitionerState: "CA",
    petitionerZip: "92501",
    petitionerPhone: "(951) 555-1234",
    petitionerEmail: "jane.doe@example.com",
    respondentFirstName: "John",
    respondentMiddleName: "B.",
    respondentLastName: "Doe",
    caseType: "dissolution",
    relationshipType: "marriage",
    marriageDate: "2015-06-20",
    hasMinorChildren: true,
    numberOfChildren: "2",
    children: [
      { firstName: "Emily", middleName: "R.", lastName: "Doe", placeOfBirth: "Riverside, CA", dateOfBirth: "2016-03-14", age: "9" },
      { firstName: "Liam", middleName: "T.", lastName: "Doe", placeOfBirth: "Riverside, CA", dateOfBirth: "2018-11-02", age: "6" },
    ],
    courthouse: "riverside",
    filingOption: "online",
    electronicSignatureName: "Jane A. Doe",
    caseNumber: "RID2400123",
    todaysDate: "2026-07-26",
  },
  fl100: {
    ...packetDefaults.fl100,
    legalRelationship: ["married"],
    residencyMet: true,
    residencyParty: "petitioner",
    dateOfSeparation: "2025-01-15",
    minorChildrenChoice: "listed",
    uccjeaAttached: true,
    groundsDivorceOrSeparation: "irreconcilable",
    legalCustodyTo: "joint",
    physicalCustodyTo: "petitioner",
    visitationTo: "respondent",
    spousalSupportTo: "petitioner",
    terminateSupportTo: "respondent",
    communityPropertyNone: false,
    communityPropertyList: "Family residence, two vehicles, joint checking account, and household furnishings.",
    separatePropertyNone: true,
    attorneyFeesFrom: "respondent",
    restoreFormerName: true,
    formerName: "Jane Alexandra Smith",
    restrainingOrdersRead: true,
  },
  fl110: { ...packetDefaults.fl110, acknowledgeRestraining: true },
  rifl036: { ...packetDefaults.rifl036, reason: "geographic", city: "Riverside", zip: "92501", date: "2026-07-26" },
  rifl011: { ...packetDefaults.rifl011, agreeEmail: true, email: "jane.doe@example.com", date: "2026-07-26" },
  fl105: {
    ...packetDefaults.fl105,
    role: "party",
    residences: [
      { fromDate: "2020-01-01", toDate: "", isCurrent: true, residence: "Riverside, CA", livedWith: "Jane A. Doe, 123 Example Street, Riverside, CA 92501", relationship: "Mother" },
    ],
    singleResidenceForAll: true,
    otherProceedings: false,
    restrainingOrders: false,
    otherPersons: false,
    pagesAttached: "0",
    date: "2026-07-26",
  },
  fl142: {
    ...packetDefaults.fl142,
    whoseSchedule: "petitioner",
    assets: {
      ...packetDefaults.fl142.assets,
      realEstate: { none: false, description: "123 Example Street, Riverside, CA 92501", sepProp: "", dateAcquired: "06/2015", grossValue: "480000", amountOwed: "260000" },
      vehicles: { none: false, description: "2019 Toyota Camry", sepProp: "", dateAcquired: "04/2019", grossValue: "18000", amountOwed: "4000" },
      checking: { none: false, description: "Example Bank checking #1234", sepProp: "", dateAcquired: "", grossValue: "6200", amountOwed: "" },
    },
    debts: {
      ...packetDefaults.fl142.debts,
      creditCards: { none: false, description: "Example Card ending 5678", sepProp: "", totalOwing: "3400", dateAcquired: "" },
    },
    continuationPages: "0",
    date: "2026-07-26",
  },
  fl150: {
    ...packetDefaults.fl150,
    employer: "Acme Corporation",
    employerAddress: "500 Market St, Riverside, CA 92501",
    employerPhone: "(951) 555-9000",
    occupation: "Office Manager",
    dateJobStarted: "2019-02-01",
    hoursPerWeek: "40",
    grossPay: "5200",
    payFrequency: "month",
    age: "38",
    completedHighSchool: true,
    yearsCollege: "4",
    collegeDegrees: "B.A. Business",
    lastTaxYear: "2025",
    taxFilingStatus: "marriedJointly",
    taxFilingJointName: "John B. Doe",
    otherPartyIncome: "6000",
    otherPartyIncomeBasis: "Based on pay stubs from prior year.",
    incomeSalary: "5200",
    incomeOther: "150",
    deductionHealthInsurance: "220",
    assetCash: "6200",
    assetOtherProperty: "480000",
    household: [
      { name: "Emily Doe", age: "9", relationship: "Daughter", grossMonthlyIncome: "0", paysExpenses: false },
      { name: "Liam Doe", age: "6", relationship: "Son", grossMonthlyIncome: "0", paysExpenses: false },
    ],
    expenseHome: "1900",
    expenseGroceries: "800",
    expenseUtilities: "300",
    expenseAuto: "350",
    numberChildrenUnder18: "2",
    timeWithMePercent: "60",
    timeWithOtherPercent: "40",
    hasChildHealthInsurance: true,
    childInsuranceCompany: "Example Health",
    childInsuranceMonthlyCost: "180",
    date: "2026-07-26",
  },
  fl140: {
    ...packetDefaults.fl140,
    whoseDisclosure: "petitioner",
    disclosureStage: "preliminary",
    attachSchedule: true,
    attachIncomeExpense: true,
    date: "2026-07-26",
  },
  fl115: {
    ...packetDefaults.fl115,
    addressServed: "789 Other Ave, Riverside, CA 92503",
    serviceMethod: "personal",
    serviceDate: "2026-07-20",
    serviceTime: "2:30 PM",
    serverName: "Chris Server",
    serverAddress: "999 Process Ln, Riverside, CA 92505",
    serverPhone: "(951) 555-7777",
    serverIsRegistered: true,
    serverRegistrationNo: "PS-12345",
    serverCounty: "Riverside",
    serverFee: "85",
    date: "2026-07-21",
  },
};
