export type PetitionFormData = {
  petitionerName: string;
  respondentName: string;
  streetAddress: string;
  city: string;
  state: string;
  zip: string;
  email: string;
  phone: string;
  relationshipStatus: "married" | "domesticPartnership" | "registeredPartnership" | "separated" | "other";
  residenceCounty: string;
  jurisdictionFacts: string;
  marriageDate: string;
  separationDate?: string;
  hasMinorChildren: boolean;
  numberOfChildren?: number;
  childrenAges?: string;
  legalGrounds: Array<"irreconcilableDifferences" | "legalSeparation" | "nullity" | "other">;
  custodyRequest: "joint" | "sole" | "other";
  visitationPlan?: string;
  childSupportRequested: boolean;
  childSupportDetails?: string;
  spousalSupportRequested: boolean;
  spousalSupportDetails?: string;
  separatePropertyClaims?: string;
  communityPropertyClaims?: string;
  otherRequests?: string;
  attachments?: string[];
};