import {
  AssetEntry,
  AssetKey,
  Child,
  DebtEntry,
  DebtKey,
  PacketFormData,
} from "@/lib/types/packet.types";

export const emptyChild = (): Child => ({
  firstName: "",
  middleName: "",
  lastName: "",
  placeOfBirth: "",
  dateOfBirth: "",
  age: "",
});

const emptyAsset = (): AssetEntry => ({
  none: false,
  description: "",
  sepProp: "",
  dateAcquired: "",
  grossValue: "",
  amountOwed: "",
});

const emptyDebt = (): DebtEntry => ({
  none: false,
  description: "",
  sepProp: "",
  totalOwing: "",
  dateAcquired: "",
});

const ASSET_KEYS: AssetKey[] = [
  "realEstate", "household", "jewelry", "vehicles", "savings", "checking",
  "creditUnion", "cash", "taxRefund", "lifeInsurance", "stocks", "retirement",
  "profitSharing", "receivables", "partnerships", "otherAssets",
];

const DEBT_KEYS: DebtKey[] = [
  "studentLoans", "taxes", "supportArrears", "unsecuredLoans", "creditCards", "otherDebts",
];

const buildAssets = () =>
  Object.fromEntries(ASSET_KEYS.map((k) => [k, emptyAsset()])) as Record<AssetKey, AssetEntry>;

const buildDebts = () =>
  Object.fromEntries(DEBT_KEYS.map((k) => [k, emptyDebt()])) as Record<DebtKey, DebtEntry>;

export const packetDefaults: PacketFormData = {
  intake: {
    petitionerFirstName: "",
    petitionerMiddleName: "",
    petitionerLastName: "",
    petitionerStreet: "",
    petitionerCity: "",
    petitionerState: "CA",
    petitionerZip: "",
    petitionerPhone: "",
    petitionerEmail: "",
    respondentFirstName: "",
    respondentMiddleName: "",
    respondentLastName: "",
    caseType: "dissolution",
    relationshipType: "marriage",
    marriageDate: "",
    hasMinorChildren: false,
    numberOfChildren: "",
    children: [],
    courthouse: "",
    filingOption: "",
    electronicSignatureName: "",
    caseNumber: "",
    todaysDate: "",
  },
  fl100: {
    amended: false,
    caseNumber: "",
    legalRelationship: [],
    residencyMet: false,
    residencyParty: "",
    residencyDpInCA: false,
    residencySameSex: false,
    petitionerLivesIn: "",
    respondentLivesIn: "",
    dateOfSeparation: "",
    dpRegistrationDate: "",
    minorChildrenChoice: "",
    childBornBeforeMarriage: false,
    uccjeaAttached: false,
    voluntaryParentage: false,
    groundsDivorceOrSeparation: "",
    groundsNullityVoid: "",
    groundsNullityVoidable: "",
    legalCustodyTo: "",
    physicalCustodyTo: "",
    visitationTo: "",
    childSupportOther: "",
    spousalSupportTo: "",
    terminateSupportTo: "",
    reserveSupportTo: "",
    spousalSupportOther: "",
    separatePropertyNone: false,
    separatePropertyList: "",
    communityPropertyNone: false,
    communityPropertyList: "",
    attorneyFeesFrom: "",
    restoreFormerName: false,
    formerName: "",
    otherRequests: "",
    restrainingOrdersRead: false,
  },
  fl110: {
    caseNumber: "",
    acknowledgeRestraining: false,
  },
  rifl036: {
    reason: "geographic",
    city: "",
    zip: "",
    otherReason: "",
    date: "",
  },
  rifl011: {
    agreeEmail: false,
    email: "",
    stopEmail: false,
    date: "",
  },
  fl105: {
    role: "",
    residences: [
      { fromDate: "", toDate: "", isCurrent: true, residence: "", livedWith: "", relationship: "" },
    ],
    singleResidenceForAll: false,
    otherProceedings: false,
    otherProceedingsDetails: "",
    restrainingOrders: false,
    restrainingOrdersDetails: "",
    otherPersons: false,
    persons: [],
    pagesAttached: "",
    date: "",
  },
  fl142: {
    whoseSchedule: "petitioner",
    caseNumber: "",
    assets: buildAssets(),
    debts: buildDebts(),
    continuationPages: "",
    date: "",
  },
  fl150: {
    caseNumber: "",
    employer: "",
    employerAddress: "",
    employerPhone: "",
    occupation: "",
    dateJobStarted: "",
    dateJobEnded: "",
    hoursPerWeek: "",
    grossPay: "",
    payFrequency: "",
    age: "",
    completedHighSchool: false,
    highestGrade: "",
    yearsCollege: "",
    collegeDegrees: "",
    lastTaxYear: "",
    taxFilingStatus: "",
    taxFilingJointName: "",
    otherPartyIncome: "",
    otherPartyIncomeBasis: "",
    incomeSalary: "",
    incomeOvertime: "",
    incomeCommissions: "",
    incomePublicAssistance: "",
    incomeSpousalSupport: "",
    incomePension: "",
    incomeSocialSecurity: "",
    incomeUnemployment: "",
    incomeOther: "",
    deductionUnionDues: "",
    deductionRetirement: "",
    deductionHealthInsurance: "",
    deductionChildSupportOther: "",
    assetCash: "",
    assetStocks: "",
    assetOtherProperty: "",
    household: [],
    expenseHome: "",
    expenseHealthCare: "",
    expenseChildCare: "",
    expenseGroceries: "",
    expenseEatingOut: "",
    expenseUtilities: "",
    expensePhone: "",
    expenseLaundry: "",
    expenseClothes: "",
    expenseEducation: "",
    expenseEntertainment: "",
    expenseAuto: "",
    expenseInsurance: "",
    expenseSavings: "",
    expenseOther: "",
    numberChildrenUnder18: "",
    timeWithMePercent: "",
    timeWithOtherPercent: "",
    hasChildHealthInsurance: false,
    childInsuranceCompany: "",
    childInsuranceMonthlyCost: "",
    date: "",
  },
  fl140: {
    whoseDisclosure: "petitioner",
    disclosureStage: "preliminary",
    attachSchedule: true,
    attachIncomeExpense: true,
    attachTaxReturns: false,
    attachMaterialFactsAssets: false,
    attachMaterialFactsObligations: false,
    attachInvestmentOpportunity: false,
    date: "",
  },
  fl115: {
    caseNumber: "",
    addressServed: "",
    serviceMethod: "",
    serviceDate: "",
    serviceTime: "",
    serverName: "",
    serverAddress: "",
    serverPhone: "",
    serverIsRegistered: false,
    serverRegistrationNo: "",
    serverCounty: "",
    serverFee: "",
    date: "",
  },
};
